/**
 * Created by kevin on 16-4-8.
 */
export const TAB_SWITCH = 'TAB_SWITCH';

export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const OPEN_DIALOG = 'OPEN_DIALOG';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const CHANGE_PROBLEM_LIST = 'CHANGE_PROBLEM_LIST';
export const CHANGE_PROBLEM = 'CHANGE_PROBLEM';

export const CHANGE_SUBMISSION_LIST = 'CHANGE_SUBMISSION_LIST';
export const CHANGE_SUBMISSION = 'CHANGE_SUBMISSION';

export const CHANGE_CONTEST_LIST = 'CHANGE_CONTEST_LIST';
export const CHANGE_CONTEST = 'CHANGE_CONTEST';
export const CHANGE_CONTEST_PROBLEM_LIST = 'CHANGE_CONTEST_PROBLEM_LIST';