/**
 * Created by kevin on 16-4-8.
 */
export const NONE = 'NONE';
export const TAB_SWITCH = 'TAB_SWITCH';

export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const OPEN_DIALOG = 'OPEN_DIALOG';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const CHANGE_PROBLEM_LIST = 'CHANGE_PROBLEM_LIST';
export const CHANGE_PROBLEM = 'CHANGE_PROBLEM';

export const CHANGE_SUBMISSION_LIST = 'CHANGE_SUBMISSION_LIST';
export const CHANGE_SUBMISSION = 'CHANGE_SUBMISSION';

export const CHANGE_CONTEST_LIST = 'CHANGE_CONTEST_LIST';
export const CHANGE_CONTEST = 'CHANGE_CONTEST';
export const CHANGE_CONTEST_PROBLEM_LIST = 'CHANGE_CONTEST_PROBLEM_LIST';

export const CHANGE_LANGUAGE_LIST = 'CHANGE_LANGUAGE_LIST';

export const CHANGE_USER_LIST = 'CHANGE_USER_LIST';
export const CHANGE_USER = 'CHANGE_USER';

export const CHANGE_STANDING_LIST = 'CHANGE_STANDING_LIST';
export const CHANGE_TOPIC_LIST = 'CHANGE_TOPIC_LIST';
export const CHANGE_TOPIC_DETAIL = 'CHANGE_TOPIC_DETAIL';