/**
 * Created by kevin on 16-4-8.
 */
export const SWITCH_TAB = 'SWITCH_TAB';
export const OPEN_LOGIN_DIALOG = 'OPEN_LOGIN_DIALOG';
export const CLOSE_LOGIN_DIALOG = 'CLOSE_LOGIN_DIALOG';

export const OPEN_REGISTER_DIALOG = 'OPEN_REGISTER_DIALOG';
export const COLSE_REGISTER_DIALOG = 'COLSE_REGISTER_DIALOG';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
